/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.InicioViews;

import Views.EstadoAprovecionViews.EstadoAprobacion;
import Views.EstadoPresupuestoViews.EstadoPresupuesto;
import Views.RolViews.Roles;
import Views.TipoPartidaViews.TipoPartida;
/**
 *
 * @author Estudiantes
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EstadoAprobacion = new javax.swing.JButton();
        EstadoPresupuesto = new javax.swing.JButton();
        Rol = new javax.swing.JButton();
        TipoPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 36)); // NOI18N
        jLabel1.setText("  CRUD");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.default.focusColor"), 3));

        EstadoAprobacion.setText("CRUD  ESTADO APROBACION");
        EstadoAprobacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoAprobacionActionPerformed(evt);
            }
        });

        EstadoPresupuesto.setText("CRUD ESTADO PRESUPUESTO");
        EstadoPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoPresupuestoActionPerformed(evt);
            }
        });

        Rol.setText("CRUD ROLES");
        Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolActionPerformed(evt);
            }
        });

        TipoPartida.setText("CRUD TIPO PARTIDA ");
        TipoPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EstadoAprobacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EstadoPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TipoPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(EstadoAprobacion)
                .addGap(18, 18, 18)
                .addComponent(EstadoPresupuesto)
                .addGap(18, 18, 18)
                .addComponent(Rol)
                .addGap(18, 18, 18)
                .addComponent(TipoPartida)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoPartidaActionPerformed
        // TODO add your handling code here: 
        TipoPartida TipoPartidaViews = new TipoPartida();
        TipoPartidaViews.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_TipoPartidaActionPerformed

    private void EstadoAprobacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoAprobacionActionPerformed
        // TODO add your handling code here:
        EstadoAprobacion EstadoAprovecionViews = new EstadoAprobacion();
        EstadoAprovecionViews.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_EstadoAprobacionActionPerformed

    private void EstadoPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoPresupuestoActionPerformed
        // TODO add your handling code here:
        EstadoPresupuesto EstadoPresupuestoViews = new EstadoPresupuesto();
        EstadoPresupuestoViews .setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_EstadoPresupuestoActionPerformed

    private void RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolActionPerformed
        // TODO add your handling code here:
        Roles RolView = new Roles();
        RolView.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_RolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EstadoAprobacion;
    private javax.swing.JButton EstadoPresupuesto;
    private javax.swing.JButton Rol;
    private javax.swing.JButton TipoPartida;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
